/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int main(void);
int add(void);

int main(void)
{
b0:;
 int t0 = add();
 int t1 = 7;
 int t2 = t0 * t1;
 return t2;
b1:;
 }

int add(void)
{
b0:;
 int t0 = 5;
 return t0;
b1:;
 }

