/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int puts(const char* s);
int main(void);

int main(void)
{
b0:;
 const char* t1 = "Hello world";
 int t0 = puts(t1);
 int t2 = 0;
 return t2;
b1:;
 }

