/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int printf(const char* , ...);
int main(void);

int main(void)
{
b0:;
 const char* t1 = "Hello %s!\n";
 const char* t2 = "World";
 int t0 = printf(t1,t2);
 int t3 = 0;
 return t3;
b1:;
 }

