/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int printf(const char* , ...);
int main(void);

int main(void)
{
 int v0; // i
b0:;
 int t0 = 0;
 v0 = t0;
 b1:;
 int t1 = v0;
 int t2 = 10;
 int t3 = t1 < t2;
 if (t3) { goto b2; } else { goto b4; }
b2:;
 const char* t5 = "Hello %d!\n";
 int t6 = v0;
 int t4 = printf(t5,t6);
 goto b3;
b3:;
 int t7 = 1;
 int t8 = v0;
 int t9 = t8 + t7;
 v0 = t9;
 goto b1;
b4:;
 b5:;
 int t10 = 0;
 return t10;
b6:;
 }

