/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int printf(const char* , ...);
int main(void);

int main(void)
{
 size_t v0; // i
b0:;
 int t0 = 0;
 v0 = t0;
 b1:;
 size_t t2 = v0;
 int t3 = 10;
 int t1 = t2 < t3;
 if (t1) { goto b2; } else { goto b4; }
b2:;
 const char* t5 = "Hello %d!\n";
 size_t t6 = v0;
 int t4 = printf(t5,t6);
 goto b3;
b3:;
 size_t t7 = v0;
 size_t t8 = 1;
 size_t t9 = t7 + t8;
 v0 = t9;
 goto b1;
b4:;
 b5:;
 int t10 = 0;
 return t10;
b6:;
 }

