/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int printf(const char* , ...);
int tryAdd(uint8_t a, uint8_t b);
int main(void);

int tryAdd(uint8_t a, uint8_t b)
{
 uint8_t v0 = a; // a
 uint8_t v1 = b; // b
b0:;
 uint8_t t0 = v0;
 int t1 = 0;
 int t2 = t0 == t1;
 if (t2) { goto b1; } else { goto b2; }
b1:;
 int t3 = 0;
 return t3;
b2:;
 goto b3;
b3:;
 uint8_t t4 = v0;
 uint8_t t5 = v1;
 uint8_t t6 = t4 + t5;
 return t6;
b4:;
 goto b3;
b5:;
 }

int main(void)
{
b0:;
 const char* t1 = "%d\n";
 int t3 = 2;
 int t4 = 3;
 int t2 = tryAdd(t3,t4);
 int t0 = printf(t1,t2);
 int t5 = 0;
 return t5;
b1:;
 }

