/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int printf(const char* , ...);
int tryAdd(uint8_t a, uint8_t b);
int main(void);

int tryAdd(uint8_t a, uint8_t b)
{
 uint8_t v0 = a; // a
 uint8_t v1 = b; // b
b0:;
 int t0 = 0;
 uint8_t t1 = v0;
 int t2 = 0;
 int t3 = t1 == t2;
 if (t3) { goto b1; } else { goto b2; }
b1:;
 int t4 = 0;
 t0 = t4;
 goto b3;
b2:;
 uint8_t t5 = v0;
 uint8_t t6 = v1;
 uint8_t t7 = t5 + t6;
 t0 = t7;
 goto b3;
b3:;
 return t0;
b4:;
 }

int main(void)
{
b0:;
 const char* t1 = "%d\n";
 int t3 = 2;
 int t4 = 3;
 int t2 = tryAdd(t3,t4);
 int t0 = printf(t1,t2);
 int t5 = 0;
 return t5;
b1:;
 }

