/* Generated by tzc */
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

int printf(const char* , ...);
int main(void);

int main(void)
{
 uint8_t v0; // a
 uint16_t v1; // b
 uint32_t v2; // c
 uint64_t v3; // d
 unsigned __int128 v4; // e
b0:;
 int t0 = 1;
 v0 = t0;
 uint8_t t1 = v0;
 int t2 = 1;
 int t3 = t1 + t2;
 v1 = t3;
 uint16_t t4 = v1;
 int t5 = 1;
 int t6 = t4 + t5;
 v2 = t6;
 uint32_t t7 = v2;
 int t8 = 1;
 int t9 = t7 + t8;
 v3 = t9;
 uint64_t t10 = v3;
 int t11 = 1;
 uint64_t t12 = t10 + t11;
 v4 = t12;
 const char* t14 = "%d\n";
 unsigned __int128 t15 = v4;
 int t13 = printf(t14,t15);
 int t16 = 0;
 return t16;
b1:;
 }

